name: deploy

env:
  DEPLOY_PACKAGE_NAME_FILE: "${{ github.sha }}.zip"
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Git clone https://github.com/pwardo/nextjs-threads.git
        uses: actions/checkout@v3

      - name: This create an env file incase we need one.
        run: |
          touch .env
          echo NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} >> .env
          echo CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} >> .env
          echo NEXT_CLERK_WEBHOOK_SECRET=${{ secrets.NEXT_CLERK_WEBHOOK_SECRET }} >> .env

          echo NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} >> .env
          echo NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} >> .env
          echo NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL }} >> .env
          echo NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL }} >> .env

          echo MONGODB_URL=${{ secrets.MONGODB_URL }} >> .env

          echo UPLOADTHING_SECRET=${{ secrets.UPLOADTHING_SECRET }} >> .env
          echo UPLOADTHING_APP_ID=${{ secrets.UPLOADTHING_APP_ID }} >> .env

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME_FILE }} .

      - name: Copy zip file to AWS Lightsail via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGTHSAIL_IP }}
          username: ${{ secrets.LIGTHSAIL_USERNAME }}
          key: ${{ secrets.LIGTHSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          source: ${{ env.DEPLOY_PACKAGE_NAME_FILE }}
          target: "/home/${{ secrets.LIGTHSAIL_USERNAME }}${{ secrets.LIGTHSAIL_APP_ROOT_DIR }}"

      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGTHSAIL_IP }}
          username: ${{ secrets.LIGTHSAIL_USERNAME }}
          key: ${{ secrets.LIGTHSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            sudo apt-get install zip unzip
            unzip -q -o "/home/${{ secrets.LIGTHSAIL_USERNAME }}${{ secrets.LIGTHSAIL_APP_ROOT_DIR }}"/${{ env.DEPLOY_PACKAGE_NAME_FILE }} -d /home/${{ secrets.LIGTHSAIL_USERNAME }}${{ secrets.LIGTHSAIL_APP_ROOT_DIR }}
            rm /home/${{ secrets.LIGTHSAIL_USERNAME }}${{ secrets.LIGTHSAIL_APP_ROOT_DIR }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }}

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
